nick8325/quickcheck

QuickCheck.cabal
The tutorial gives a nice overview on how to use QuickCheck.
=> Include link to 24 Days of Hackage tutorial

Test/QuickCheck/Arbitrary.hs
These were warned by GHC HEAD (v7.11.20150928)
=> Remove redundant constraints

.travis.yml, QuickCheck.cabal, tests/GCoArbitraryExample.hs, tests/GShrinkExample.hs
Resolves https://github.com/nick8325/quickcheck/issues/74
=> Drop support for ghc < 7

.travis.yml
supersedes https://github.com/nick8325/quickcheck/pull/50
=> Use hvr's travis setup

QuickCheck.cabal
Includes commit from https://github.com/nick8325/quickcheck/pull/75
=> Use nats dependency with older compilers / base

Test/QuickCheck.hs
Isn't this supposed to be a `doctest`?
=> Funny typo

Test/QuickCheck/Arbitrary.hs
I needed Arbitrary instances for lare tuples so I've added them
Only thing that worries me is shrink. Cross product of all possible shrinks for all tuple elements for say 10-tuple could become LARGE
=> Add Aribtrary instances up to 10-tuples

.travis.yml, Test/QuickCheck/All.hs
Resolves https://github.com/nick8325/quickcheck/issues/99
=> Use correct in TH code

Test/QuickCheck/Property.hs
=> Testable (Gen prop) should be always tried again

Test/QuickCheck/Function.hs, changelog
=> Added Fn2, Fn3, apply2, apply3

Test/QuickCheck/Arbitrary.hs, tests/ShrinkMap.hs
I find using this pattern quite often
=> Add shrinkMap and shrinkMapBy

.gitignore, Test/QuickCheck/State.hs, Test/QuickCheck/Test.hs, changelog, tests/Generators.hs
=> Add Args.maxShrinks

.gitignore, Test/QuickCheck/Exception.hs, Test/QuickCheck/State.hs, Test/QuickCheck/Test.hs, changelog, tests/Generators.hs
=> Don't catch async exceptions

QuickCheck.cabal
After reviewing existing online material about QuickCheck I wrote a comprehensive tutorial to fill in the gaps and unify the information. This pull request adds a link to it from the haddock docs.
=> Link to detailed QuickCheck tutorial

.travis.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Add GHC 8.0.2 to Travis

Test/QuickCheck/Arbitrary.hs
`generic-random` is a nice library for automatic creation of arbitrary instances using Generics. The library is described in more depth on Brent Yorgey's blog: https://byorgey.wordpress.com/2016/09/20/the-generic-random-library-part-1-simple-generic-arbitrary-instances/
=> Add link to generic-random in the docs

Test/QuickCheck.hs, Test/QuickCheck/All.hs
Motivated by https://stackoverflow.com/questions/47953171/using-the-quickcheckall-function-in-tasty-quickcheck
=> Make a way to extract properties from a module in a list

Test/QuickCheck.hs, Test/QuickCheck/Arbitrary.hs
=> Combinators for products

Test/QuickCheck.hs, Test/QuickCheck/Function.hs
Resolves https://github.com/nick8325/quickcheck/issues/257
=> Add functionVoid

src/Test/QuickCheck/Arbitrary.hs, src/Test/QuickCheck/Function.hs
Code taken from https://github.com/phadej/qc-instances/pull/30
(sorry it took so long to come to it).
Small change is to use shuffle in arbPartition so they
won't be "tail heavy".
Also add Function instance which was missing from
quickcheck-instances
=> Add Tree instances

src/Test/QuickCheck/Gen/Unsafe.hs
=> Fix `promote` doing an unnecessary split

src/Test/QuickCheck.hs
=> Document GHCi monomorphism pitfall

QuickCheck.cabal, src/Test/QuickCheck/Features.hs, src/Test/QuickCheck/Property.hs, src/Test/QuickCheck/Test.hs, tests/Misc.hs
=> Collect and print non-covered classes

src/Test/QuickCheck/Test.hs, tests/Misc.hs
=> Fix `discard`:ed shrink list failing without a reason

src/Test/QuickCheck/Test.hs
=> fix overflow bug in discard ratio calculation

src/Test/QuickCheck/Monadic.hs
I found myself needing these functions on multiple occasions and thought that others might benefit from them as well. Please, let me know if there is anything you'd like me to change in order to get this PR merged.
Use case for those functions is pretty straightforward:
```haskell
λ> quickCheck $ \ x -> assertException (==DivideByZero) (x `div` 0)
+++ OK, passed 100 tests.
```
I thought at first `Test.QuickCheck.Exception` would be a good home for these functions, but it'll be too hard to avoid import cycles.
=> Introduced assertException and assertDeepException

src/Test/QuickCheck/Arbitrary.hs
=> Hack to get around underflow issues in `arbitrarySizedIntegral`

src/Test/QuickCheck/Exception.hs, src/Test/QuickCheck/Gen.hs, tests/Misc.hs
closes #392 
There is no good approach to fixing `generate`... Ideas welcome.
=> Fix `sample discard` crashing

QuickCheck.cabal, changelog
Thoughts welcome, are there any outstanding PRs that we should try to incorporate in this release? I would be happy if we could get #387 and maybe #376 (but I'm not sure if the design work is done there yet).
=> Version bump to 2.15

src/Test/QuickCheck/Function.hs
=> export `mkFun`

.github/workflows/microhs-ci.yml, QuickCheck.cabal, src/Test/QuickCheck/Arbitrary.hs, src/Test/QuickCheck/Exception.hs, src/Test/QuickCheck/Function.hs, src/Test/QuickCheck/Property.hs
Various minor changes for MicroHs
=> Make it compile with MicroHs

src/Test/QuickCheck/Arbitrary.hs
=> No non-negative block buffer modes
