nick8325/quickcheck

Test/QuickCheck/All.hs
This pull request was motivated when I tried using `quickCheckAll` in GHC 7.10, which uses `tempate-haskell-2.10.0.0`. Introduced in `template-haskell-2.10.0.0` was [a change](https://downloads.haskell.org/~ghc/7.10.1-rc1/docs/html/users_guide/release-7-10-1.html#idp5794496) in which all reified `TyVarBndr`s are now `KindedTV`s. This causes some `QuickCheck` code which worked in previous GHCs to fail with GHC 7.10. As an example, when you run this code on GHC 7.10:
```haskell
{-# LANGUAGE TemplateHaskell #-}
module Main (main) where
import Test.QuickCheck (Arbitrary, quickCheckAll)
prop_elem :: (Arbitrary a, Eq a, Show a) => a -> [a] -> Bool
prop_elem a as = a `elem` as
$(return [])
main :: IO ()
main = $quickCheckAll >>= print
```
you encounter this error:
```
Exception when trying to …
```
=> Allow single star-kinded TyVarBndrs in quickCheckAll

Test/QuickCheck/Gen.hs
I find these 3 combinators useful, see if there are good enough to be merged into this repo :)
* `subsetOf` generates a subset of the given list.
* `selectOneFrom` is an extension of `elements`: it not only returns the selected element, but also the rest of the choices. this would make sampling without replacement a little bit easier.
* `shuffled` returns a shuffled version of the given list. Additionally, `take n <$> shuffed xs` will then be randomly choosing up to `n` values from `xs` without replacement.
=> adding new generator combinators: subsetOf, selectOneFrom, shuffled

Test/QuickCheck/Arbitrary.hs
`-XOverlappedInstances` is deprecated and is actually unnecessary here, at least on 7.10.
=> Fix a GHC 7.10 warning.

Test/QuickCheck/All.hs, tests/Weird.hs
Fixes #63
Test by loading `tests/Weird.hs` in GHCi; each of the following cases will be run by TemplateHaskell, failing with an error if any isn't right:
- Monomorphising polymorphic variables, via `$quickCheckAll`. This is the existing behaviour, although it seemed to be untested. I've added `prop_poly` to test this.
- Monomorphising prefix data constructors. I've added `dummyRun` to test this.
- Monomorphising infix data constructors, ie. those which begin with `:`. I've added `monoCons` to test this.
- Monomorphising `[]`, which seems to defy the prefix and infix rules given in the Haskell 2010 Language Report. I've added `monoNil` to test this.
There are no regressions from `cabal test`, although that only seems to run one of the examples.
This was tested with GHC 7.10.2 on NixOS …
=> Distinguish between variables and constructors

Test/QuickCheck/Modifiers.hs
Weaken Ord to Eq, the instance did not make use of the Ord constraint.
=> Weaken (Ord a) constraint on Arbitrary (NonZero a)

QuickCheck.cabal, Test/QuickCheck/All.hs
While at it, this also makes the QuickCheck package convenient for
unregisterised and/or cross-compilers lacking TH support with latest
Cabal solvers by declaring the need for Template-Haskell in
`other-extensions` as a dependency, which then directs the cabal solver
toggle off the TH support flag if that extension is not advertised by
GHC.
=> Make compatible with template-haskell 2.11 / GHC 8.0

QuickCheck.cabal
Haste is offended by C dependencies and Template Haskell, so let's shut them off when building with Haste.
=> Don't depend on Template Haskell or tf-random when installed using Haste.

Test/QuickCheck/Test.hs
There is a space leak with the label function. Specifically, given the following program:
```
{-# LANGUAGE ScopedTypeVariables #-}
import Test.QuickCheck
main :: IO ()
main = do
Success{} <- quickCheckWithResult stdArgs{maxSuccess=10000} $ \(p :: Double) -> label "foo" True
print "done"
```
Running it I get:
```
$ ghc --make Main.hs -rtsopts && Main +RTS -K1K
...
Linking Main.exe ...
Main: Stack space overflow: current size 33624 bytes.
Main: Use `+RTS -Ksize -RTS' to increase it.
```
The `-K1K` flag limits the stack, which makes it easier to detect the space leak. Under normal circumstances it just increases memory usage and makes things go unnecessarily slower without failing.
After applying the patch the space leak disappears. Originally spotted by @jacereda and reported at …
=> Fix a spaceleak with label function

Test/QuickCheck/Gen.hs
I often find myself needing to generate a random value over the entire natural range of an instance of `Random a`. Additionally, some instances of `Random` ignore the range argument of `randomR` and using the `choose` combinator doesn't make sense for these types, e.g. Data.UUID. This pull request adds a `chooseAny` combinator defined as
```haskell
chooseAny :: Random a => Gen a
```
=> Add a `chooseAny` Gen combinator

QuickCheck.cabal, Test/QuickCheck/Gen/Class.hs
* Add an mtl-style `MonadGen` class for monads int which one can
lift `Gen` values.
* Add the obvious instances. ~~I did not have the time to consider
whether there are sensible instances available for `ContT` or
even the version of `ListT` in `transformers`, so I left those
out.~~ I don't know if the `transformers` `ListT` makes sense for this,
so I left it out.
Fixes #107
=> Add MonadGen class

Test/QuickCheck.hs, Test/QuickCheck/Function.hs, Test/QuickCheck/Gen/Unsafe.hs, Test/QuickCheck/Monadic.hs, Test/QuickCheck/Poly.hs, changelog
- Export `Fun` type, `apply`, `Function(..)`, and `functionMap` from `Test.QuickCheck`
- I often find I need just `Fun` and `apply` when writing test-suites. It could be very convenient if they are re-exported from `Test.QuickCheck`.
- I intentionally didn't re-export `Fun` constructor
-  For this I made `Test.QuickCheck.Function` and `Test.QuickCheck.Poly` *Safe*
- Also added documentation to 'Fun' and 'apply', so `Test.QuickCheck` haddock have something about them.
- Added a type to 'Fn', for some reason I was getting `(t -> t) -> Fun t t` with GHC7.10.3 (in GHC-8.0 it seems to be fixed)
- You can see this issue in old haddocks: http://hackage.haskell.org/package/QuickCheck-2.8.2/docs/Test-QuickCheck-Function.html#v:Fn
=> Export fun

QuickCheck.cabal
This isn't catched as we don't test with anything else as GHC
=> Fix else: -> else

Test/QuickCheck/Arbitrary.hs
Add missing Arbitrary instances for data types from base
- Data types from Foreign.C.Types
- System.Exit.ExitCode
- WrappedMonad and WrappedArrow
=> Base instances

Test/QuickCheck/Arbitrary.hs
I left out tuples and monoid/semigroup (and some other) wrappers.
Also changed the `NonEmpty` shrink a bit, now it's better (no filtering).
=> Add more Arbitrary1 instances

Test/QuickCheck/Monadic.hs, changelog
=> Make `Monadic` functions not ignore the `a`s returned; use `()` instead

Test/QuickCheck.hs, Test/QuickCheck/Gen.hs
This is a trivial little definition, but it helps write slightly nicer-looking generators.
As the docs in this PR demonstrate, one can rewrite
```haskell
listOf gen = sized $ \n -> do
k <- choose (0, n)
vectorOf k gen
```
as
```haskell
listOf gen = do
n <- genSize
k <- choose (0, n)
vectorOf k gen
```
The latter style makes more sense to me, and I think it's easier to teach, so it'd be nice to have it in the library :)
=> Add genSize :: Gen Int

Test/QuickCheck/Arbitrary.hs
A minor thing: when you build the current version of `QuickCheck` on GHC < 7.10, it emits warnings. Example [here](https://travis-ci.org/sol/doctest/jobs/191673800#L806):
```
Test/QuickCheck/Arbitrary.hs:317:10: Warning: Unrecognised pragma
Test/QuickCheck/Arbitrary.hs:320:10: Warning: Unrecognised pragma
```
That's because GHC didn't support the `{-# OVERLAPPING #-}` pragma until GHC 7.10 (before then, it just used the `-XOverlappingInstances` extension. To avoid this, I used CPP to make `OVERLAPPING_` expand to `{-# OVERLAPPING #-}` on recent GHCs, but expand to nothing on older GHCs. This is the same trick that [`aeson` uses.](https://github.com/bos/aeson/blob/d470ac61874b4dc80b88a44a0c2d967430a8d5ce/include/overlapping-compat.h)
=> Don't use {-# OVERLAPPING #-} pragmas on GHC < 7.10

Test/QuickCheck/Test.hs
Document that `quickCheck` does 100 tests by default and that this is
an arbitrary choice, and explain how to change the default.
Fixes https://github.com/nick8325/quickcheck/issues/121.
=> Document default number of tests (Fixes #121).

Test/QuickCheck/Function.hs
There are instances of `Function` for `Word8/16/32/64`, but not for `Word` itself.
=> Add missing Function Word instance

QuickCheck.cabal, Test/QuickCheck/Arbitrary.hs, Test/QuickCheck/Function.hs, Test/QuickCheck/Modifiers.hs, changelog
Related to #158. See https://github.com/phadej/qc-instances/pull/2 for corresponding PR in `quickcheck-instances`.
cc @RyanGlScott
=> Remove light flag; migrate instances to quickcheck-instances

Test/QuickCheck.hs
Data constructor `Fun(Fun)` is not exported by `QuickCheck.hs`. This PR fix this issue.
=> Exported data constructor `Fun(Fun)`

Test/QuickCheck/Gen.hs
`ap` calls `(>>=)` twice, and the third seed is discarded by `return`:
ap mf mx = do f <- mf ; x <- mx ; return (f x)
Does this count as a breaking change? Does QuickCheck make stability guarantees that allow storing test cases as seeds?
=> Make (<*>) split only once

Test/QuickCheck/Arbitrary.hs
The current behaviour of `shrink` for fractional / floating numbers is not particularly useful: it only tries replacing the number with _integers_, but that often leads to quite different behaviour of numerical functions.
I've implemented an algorithm based on [continued fractions](https://en.wikipedia.org/wiki/Continued_fraction), which generates an asymptotic sequence that actually approximates the original number, and also behaves more sensibly for infinities etc..
Examples:
```
*Test.QuickCheck.Arbitrary> shrink (32/7)
[0.0,2.0,3.0,4.0,5.0,4.5,4.6]
*Test.QuickCheck.Arbitrary> shrink (-5.23)
[0.0,3.0,4.0,5.0,5.5,5.333333333333333,5.25,5.2,5.222222222222222,5.230769230769231,5.229508196721311,5.2298850574712645,-3.0,-4.0,-5.0,-5.5,-5.333333333333333,-5.25,-5.2,-5.222222222222222,-5.23076 …
```
=> Shrink fractions in an asymptotic manner

Test/QuickCheck/Gen.hs
Simple change adding a `MonadFix` instance for `Gen`
=> Add MonadFix instance for Gen

Test/QuickCheck.hs
@nick8325 it would be very great to have a `2.11.5` release with this.
=> Coarbitrary exists, even without generics

Test/QuickCheck.hs, Test/QuickCheck/Function.hs, Test/QuickCheck/Modifiers.hs, Test/QuickCheck/Property.hs
I think use "Falsifiable" here is not very appropriate, since it emphasize the **inherent possibility** that a statement can be proven false. In our case, the proposition is already shown to be False, and we have found an obvious evidence about that, so I think "Falsism" could be better here.
> Falsifiability or refutability of a statement, hypothesis, or theory is the inherent possibility that it can be proven false. A statement is called falsifiable if it is possible to conceive of an observation or an argument which negates the statement in question.
> A falsism is a claim that is clearly and self-evidently wrong. A falsism is usually used merely as a reminder or as a rhetorical or literary device. An example is "pigs can fly." It is the opposite of truism.
=> replace "Falsifiable" in error message into some better word

QuickCheck.cabal
- Lower bound: prior random-1.0.1.0 it wasn't `Trustworthy`, so compiling QuickCheck fails
- Upper bound: `random-1.2` (or whatever next major) will change things, though it's not clear when it will be released. Better to have bounds in place, so we won't need to make revisions later.
=> Add bounds for random

QuickCheck.cabal
... to allow `random` bundled with GHC-7.0.x
=> Relax random lower bound with GHC-7.0

Test/QuickCheck/Function.hs
These allows constructing `:->` without looping though `Function` type-class
=> Export functionEitherWith and functionPairWith

Test/QuickCheck/Gen.hs
* Write custom `(*>)`, `(<*)`, and `(>>)` implementations for `Gen`;
these can avoid splitting the seed. They're also essentially useless,
but they could show up if someone uses `Applicative`-generic
operations of some sort.
* Move the implementation from `return` to `pure` for `Gen`, rendering
the `return` implementation "canonical".
=> Improve Gen instances

Test/QuickCheck/Arbitrary.hs
By standard, Unicode has sixty-six noncharacters, which can be incorrectly
interpreted by different applications. To prevent possible troubles,
characters with NotAssigned property shouldn't be generated.
=> Fix non-valid unicode issue

Test/QuickCheck/Arbitrary.hs
I am using `genericShrink` but require `RecursivelyShrink` and `GSubterms` to be exported for my type signatures.
Would you be open to exporting these types?
=> Export RecursivelyShrink & GSubterms

QuickCheck.cabal, Test/QuickCheck/Random.hs, changelog
This PR implements compatibility with `random-1.2.0`, which was finally released today
=> Compatibility with new version of random

.travis.yml, QuickCheck.cabal, Test/QuickCheck/Gen.hs, Test/QuickCheck/Random.hs
splitmix-0.1 dropped dependency on random. But that's
a non-issue, as QuickCheck doesn't use any `random` instances
of `SMGen`, we only need to implement `RandomGen QCGen`
in terms of splitmix combinators
Related: https://github.com/phadej/splitmix/issues/34
EDIT: I made revisions to `QuickCheck-2.13 .. 2.14` to disallow `splitmix-0.1` (which doesn't have `RangomGen` instance anymore), e.g. https://hackage.haskell.org/package/QuickCheck-2.14/revisions/
EDIT2: Travis job https://travis-ci.org/github/nick8325/quickcheck/builds/692237337
=> Use splitmix-0.0.5's nextInteger, and support splitmix-0.1 (i.e. don't rely on RandomGen SMGen instance)

src/Test/QuickCheck/All.hs
(1) Fix bad unipattern in lambda
(2) Update patterns for updated `TyVarBndr` from template-haskell-2.17.0
While opening this PR I noticed that #311 also addresses (2), however it addresses (1) differently and apparently incorrectly.
The uni-patterned lambda would previously incorrectly fail on `KindedTV nm StarT` and #311 unnecessarily reproduces this failure.
This patch is also shorter and clearer.
=> Support GHC-9.0 (template-haskell-2.17) and allow `StarT`-kinded TVs

src/Test/QuickCheck/Arbitrary.hs, src/Test/QuickCheck/Function.hs
These are similar to the instances for bools and a pair of bools *but* we shrink towards `LF` because, according to `Newline`'s [documentation in base](https://hackage.haskell.org/package/base-4.14.0.0/docs/System-IO.html#g:25), Haskell assumes `\n` in its programs, and `LF` means we don't need any translations.
`CRLF`, means we do need to translate, meaning it will normally be the more complex case.
By implementing `Arbitrary`, `CoArbitrary` and `Function` instances for both [`Newline`](https://hackage.haskell.org/package/base-4.14.0.0/docs/System-IO.html#t:Newline) and [`NewlineMode`](https://hackage.haskell.org/package/base-4.14.0.0/docs/System-IO.html#t:NewlineMode), this closes issue #322
=> Implemented instances for Newline and NewlineMode

QuickCheck.cabal, src/Test/QuickCheck/All.hs
So it isn't triggered by cabal-solver automatically.
This patch also makes use of TemplateHaskellQuotes extension on GHC-8.0+
https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html?highlight=templatehaskellquotes#extension-TemplateHaskellQuotes
This extension allows to make some quotes, even
when GHC doesn't support TemplateHaskell (e.g. ghc-stage1).
This way template haskell functionality can be always compiled.
This way making `templateHaskell` flag manual doesn't hurt,
as its default `True` value shouldn't pose problems.
=> Make templateHaskell flag manual

README
The `cabal install` way suggested 10+ years ago before the advent of sandboxed projects.
=> Fix installation instructions in README

src/Test/QuickCheck.hs, src/Test/QuickCheck/Property.hs
Consider an algorithm with good average case complexity, but bad worst-case one. (QuickSort with its  _O_ (_n_ · log _n_) runtime on average but worst-case _O_ (_n_<sup>2</sup>) would be an example; in the actual application I'm working on right now, it's actually more like quadratic vs. exponential!)
So, if we QuickCheck this it'll usually work just fine and, well, _quickly_, even for long lists – but sometimes QuickCheck will generate a sorted or mostly-sorted one, which dramatically slows down the runtime. This means the test suite has a very nondeterministic runtime – in my case, the test in question usually does 500 runs in 0.1 seconds, but then sometimes it takes 10 seconds for just a single run, and gigabytes of memory. This is not all that bad while I'm working on my own machine, …
=> A way to timeout tests without failing.

src/Test/QuickCheck/Arbitrary.hs
Closes #295, making maximal denominator dependent on `size` instead of being fixed to `9999999999999`. 
```haskell
> sample (arbitrarySizedFractional :: Gen Rational)
0 % 1
(-1) % 1
3 % 4
4 % 3
(-1) % 1
8 % 5
1 % 1
(-3) % 2
4 % 7
(-2) % 3
(-1) % 1
```
=> Generate Rational numbers with smaller denominators

src/Test/QuickCheck/Arbitrary.hs, src/Test/QuickCheck/Gen.hs, tests/Generators.hs
Tries to address comments in https://github.com/nick8325/quickcheck/issues/295
and https://github.com/nick8325/quickcheck/pull/296
Doesn't change how arbitrarySizedFractional works.
Now it is only used for (Ratio a) instance.
Also two properties which should fail everytime:
the Double generator has a chance of generating same values,
and it also hits values which break addition associativity.
---
My take on #295
=> Tweak Float and Double Arbitrary Instances.

src/Test/QuickCheck/All.hs, src/Test/QuickCheck/Features.hs, src/Test/QuickCheck/Gen.hs, src/Test/QuickCheck/Text.hs, tests/Generators.hs, tests/Split.hs
Future GHCs will monomorphise `Data.List`, returning its API to pre-FTP times and encouraging qualified import of `Data.List`, similar to other containers. See [MR 5304](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5304) for more information. While this change has not been released yet, it already affects quality of life of folks testing GHC HEAD. The proposed patch is rather non-intrusive and backwards-compatible, so I suggest it would not hurt to merge it early.
CC @phadej
=> Prepare for monomorphic Data.List

src/Test/QuickCheck/Function.hs
Hi. Without the added `COMPLETE` pragmas[^1], usage of `Fn`, `Fn2` or `Fn3` result in a warning such as
```
Pattern match(es) are non-exhaustive
In an equation for ‘prop_7’: Patterns not matched: (Fun _ _) _
```
if `-Wincomplete-patterns` is enabled.
[^1]: https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pragmas.html#complete-pragmas
=> Add COMPLETE pragmas for the pattern synonyms

src/Test/QuickCheck.hs, src/Test/QuickCheck/Arbitrary.hs
This PR adds a new function **`shrinkBoundedEnum`**, which should resolve issue https://github.com/nick8325/quickcheck/issues/343.
The `shrinkBoundedEnum` function provides a counterpart to the pre-existing [`arbitraryBoundedEnum`](https://hackage.haskell.org/package/QuickCheck-2.14.2/docs/Test-QuickCheck.html#v:arbitraryBoundedEnum) function. Together, they can be used to define a complete `Arbitrary` instance for a bounded enumeration data type.
For example, let's say we have the following (admittedly contrived) type:
```hs
data MyEnum
= E00 | E01 | E02 | E03 | E04 | E05 | E06 | E07 | E08 | E09
| E10 | E11 | E12 | E13 | E14 | E15 | E16 | E17 | E18 | E19
| E20 | E21 | E22 | E23 | E24 | E25 | E26 | E27 | E28 | E29
| E30 | E31 | E32 | E33 | E34 | E35 | E36 | E37 | E38 | E39
| E40 | E41 | …
```
=> Add `shrinkBoundedEnum` function.

src/Test/QuickCheck/Text.hs
`Test.QuickCheck.Text.putTemp` is used a tight loop, updating progress after each test iteration. For a cheap property `putTemp` itself can contribute significantly to the execution time. The new implementation emits roughly twice less characters and thus makes this overhead slightly less pronounced.
@nick8325 it would be great if this can fit into the next release.
=> Speed up Test.QuickCheck.Text.putTemp

QuickCheck.cabal, src/Test/QuickCheck.hs, src/Test/QuickCheck/Property.hs, src/Test/QuickCheck/State.hs, src/Test/QuickCheck/Test.hs, tests/DiscardRatio.hs
=> Add `withDiscardRatio` with a similar interface to `withMaxSuccess`

.github/workflows/haskell-ci.yml, .github/workflows/hugs-ci.yml, QuickCheck.cabal
I _tried_ to simplify the CI script using `setup-haskell/install` but a combination of things makes that tricky. Firstly, they are aiming to drop support for older versions of GHC (specifically anything older than 8) and secondly for whatever reason I couldn't get it to reliably install older ghc versions that require ubuntu-18.04 rather than 20.04 in the CI and eventually I just gave up.
=> Clarify and bump supported GHC versions

src/Test/QuickCheck/Arbitrary.hs
As per the following documentation for how OVERLAPPING resolves (that I'm 99% sure is the same across all GHC versions) https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/type-class-extensions.html#instance-overlap
the way that ghc resolves `OVERLAPPING` pragmas is that an instance that is `OVERLAPPING` will be chosen over one that isn't. It's not clear why the old code ever worked, possibly because `GSubtermsIncl (K1 i a) a` is a substitution of `GSubtermsIncl (K1 i a) b`...
Anway, with this change it's explicit that the `GSubtermsIncl (K1 i a) a` instance will be chosen over the `GSubtermsIncl (K1 i a) b` instance.
=> Fix ambiguous use of `OVERLAPPING` instances in `genericShrink`

QuickCheck.cabal, src/Test/QuickCheck/Features.hs, src/Test/QuickCheck/State.hs, src/Test/QuickCheck/Test.hs, tests/DiscardRatio.hs
=> Fix discard ratio and maxSuccess interacting poorly

src/Test/QuickCheck/Modifiers.hs
Currently `Negative` and `Positive` have `arbitrary` instances which are inconsistent with each other.
`Positive` generates an arbitrary, takes its absolute value, and checks that it is greater than 0; while `Negative` just checks the value is less than zero.
One would expect that the instance would behave like:
```haskell
arbitrary = fmap (Negative . negate . getPositive) arbitrary
```
however, because of the differences in the implementations, it does not.
This MR would make the two have consistent behavior by adjusting `Negative`'s arbitrary instance to have parity with `Positive`'s instance.
The alternative could be done, adjusting `Positive`'s instance to match that of `Negative`, but I chose to adjust it this way since the definition of arbitrary for `Positive` rejects fewer values.
=> Make Negative's arbitrary instance work like that of Positive

QuickCheck.cabal, src/Test/QuickCheck/Arbitrary.hs, tests/Strictness.hs
Strict and lazy Maps share the same type so it's not possible to have separate instances for them. The existing instance uses the lazy interface and thus produces a map containing lazy values even when the client is using the strict interface. This is a violation of the invariant of a strict Map, whereas there's no invariant to be violated with a lazy Map. It seems better, therefore, to make the instance default to producing strict values.
Note that strict maps evaluate their values only to WHNF, so a `Map Int (Maybe Char)` would still contain thunks.
If introducing a dependency on `nothunks` (even if only for testing) might be a problem, the commit containing the test can just be dropped. I added it mainly as a way of proving to myself that the fix works. (The test fails without the …
=> Make Arbitrary Map instances strict

src/Test/QuickCheck/Test.hs, tests/Misc.hs
Previously `withMaxSuccess` was discarded by `checkCoverage`. This is unfortunate because there are legitimate use cases for having both turned on at the same time. This PR fixes that. Furthermore we fix an unfortunate interaction between `discard` and `checkCoverage`.
Closes #382
=> Fix the interaction between `checkCoverage` and `maxSuccess` and `discard`

src/Test/QuickCheck.hs, src/Test/QuickCheck/Property.hs, src/Test/QuickCheck/Test.hs
The lack of actual values returned by `quickCheck` when a property fails has been a long standing friction. This PR introduces a simple combinator `withCounterexample :: (Typeable a, Show a, Testable prop) => a -> prop -> Property` that lets you "export" data to the `Failure` result of a property.
closes #117 
closes #310
=> Add `withCounterexample` to get a re-useable handle on counterexamples

src/Test/QuickCheck/Test.hs
This will help in the future to avoid situations like https://github.com/hspec/hspec/issues/883 for Hspec.
=> Add `Test.QuickCheck.Test.formatTestCount`

src/Test/QuickCheck/Property.hs, tests/DiscardRatio.hs
I made a dumb-dumb in a previous PR that changed the strictness of `classify`, which resulted in poor interaction with `discard`. This fixes that.
closes #406
=> Fix strictness of classify

src/Test/QuickCheck/Property.hs
This is particularly useful in ghc 9.10 and up, where `displayException` shows the attached annotations, including backtraces (if any).
=> Use `displayException` instead of `show`

src/Test/QuickCheck.hs, src/Test/QuickCheck/Arbitrary.hs, src/Test/QuickCheck/Gen.hs, src/Test/QuickCheck/Modifiers.hs, src/Test/QuickCheck/Monoids.hs, src/Test/QuickCheck/Property.hs, src/Test/QuickCheck/State.hs, src/Test/QuickCheck/Test.hs
Fix all broken Haddock links. Now Haddock doesn't emit any warnings about out-of-scope identifiers. Warnings about unknown link destinations more complicated to resolve and are not handled in this PR.
=> Resolve Haddock out-of-scope identifier warnings

QuickCheck.cabal
This PR adds support for random-1.3.
There's no code changes; hence no need for a new release (just a Hackage revision).
=> Support for random-1.3

QuickCheck.cabal, src/Test/QuickCheck.hs, src/Test/QuickCheck/Property.hs, src/Test/QuickCheck/State.hs, tests/WithProgress.hs
In an effort to chuck some of the testing frameworks (Tasty, Hspec) out of the internals, I add `withProgress`. Their usage of the internals seemed to be quite innocent (primarily inspecting the testing state to report the current progress by themselves). Here's a combinator that gives an alternative way of doing this.
E.g. Tasty currently does this
```Haskell
import qualified Test.QuickCheck as QC
import qualified Test.QuickCheck.Property as QCP
import qualified Test.QuickCheck.State as QC
quickCheck :: (Progress -> IO ())
-> QC.Args
-> QC.Property
-> IO QC.Result
quickCheck yieldProgress args
= (.) (QC.quickCheckWithResult args)
$ QCP.callback
$ QCP.PostTest QCP.NotCounterexample
$ \st@QC.MkState {QC.maxSuccessTests, QC.numSuccessTests} _ ->
yieldProgress $
if QC.numTotTryShrinks st > 0 …
```
=> add withProgress to make testing frameworks get out of the internals
